
const SHOPLIST='SHOPLIST';
const FIRST='FIRST';
const EXTENDS="EXTENDS"
const VOUCHERLIST="VOUCHERLIST"
const SELECTDATE="SELECTDATE"
const O2OTOTAL="O2OTOTAL"
const CREATERROR="CREATERROR"
export {SHOPLIST,FIRST,EXTENDS,VOUCHERLIST,SELECTDATE,O2OTOTAL,CREATERROR}